# 인덱싱과 슬라이싱을 이용한 배열의 원소 조회

## 배열 인덱싱(Indexing)
- ### index
    - 배열내의 원소의 식별번호
    - 0부터 시작
    - 뒤에서부터 -1로 시작
- ### indexing 
    – index를 이용해 원소 조회
    - [] 표기법 사용
- ### 구문 
    - ndarray[index]
    - 양수는 지정한 index의 값을 조회한다. 
    - 음수는 뒤부터 조회한다. 
        - 마지막 index가 -1
    - 2차원배열의 경우 
        - arr[행index, 열index]
        - 파이썬 리스트와 차이점 (list[행][열])
    - N차원 배열의 경우
        - arr[0축 index, 1축 index, ..., n축 index]
- ### 팬시(fancy) 인덱싱
    - **여러개의 원소를 한번에 조회**할 경우 리스트에 담아 전달한다.
    - 다차원 배열의 경우 각 축별로 list로 지정
    - `arr[[1,2,3,4,5]]`
        - 1차원 배열(vector): 1,2,3,4,5 번 index의 원소들 한번에 조회
    - `arr[[0,3],[ 1,4]]`
        - [0,3] - 1번축 index list, [1,4] - 2번축 index list
        - 2차원 배열(matrix): [0,1], [3,4] 의 원소들 조회

In [1]:
lst = [
    [1,2,3],
    [4,5,6]
]

lst[0][1]

2

In [2]:
import numpy as np

In [3]:
a = np.array(lst)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a[0,1]

2

In [5]:
b = np.arange(12).reshape(2,2,3)
print(b.shape)
b

(2, 2, 3)


array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [9]:
print(b[0][0][0],b[0,0,0])

0 0


In [10]:
b[1,0,1]

7

In [12]:
print(b[1,0])

[6 7 8]


In [13]:
arr = np.arange(10)
arr # 1차원

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr[[0,2]] #안의 []는 리스트로 묶어주라는 의미

array([0, 2])

In [17]:
arr[[0,5,7]]

array([0, 5, 7])

In [18]:
arr2 = np.arange(12).reshape(3,4)
arr2.shape

(3, 4)

In [19]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
arr2[0,1]

1

In [26]:
arr2[2,3]

11

In [27]:
# 1,6
# arr2[0축 , 1축]
print(arr2[[0,2],[1,3]])

[ 1 11]


In [30]:
print(arr2[[1,2,1],[0,1,3]])

[4 9 7]


In [ ]:
arr2[1,0], arr2[2,1], arr2[1,3]

In [31]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr[1] = 100 # 값 변경(대입)
arr

array([  0, 100,   2,   3,   4,   5,   6,   7,   8,   9])

In [33]:
arr[2], arr[4] = 200,400 # 튜플 대입
arr

array([  0, 100, 200,   3, 400,   5,   6,   7,   8,   9])

In [34]:
arr[[5,7]] = 500, 700
arr

array([  0, 100, 200,   3, 400, 500,   6, 700,   8,   9])

## 슬라이싱
- 배열의 부분 집합을 하위배열로 조회 및 변경하는 방식
- ndarry[start : stop : step ]
    - start : 시작 인덱스. 기본값 0
    - stop : 끝 index. stop은 포함하지 않는다. 기본값 마지막 index
    - step : 증감 간격. 기본값 1)

In [35]:
arr = np.arange(100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [36]:
arr[3:10]

array([3, 4, 5, 6, 7, 8, 9])

In [37]:
arr[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
arr[50:]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [39]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [40]:
arr[::10]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [41]:
arr[50:20:-1] # step 음수: 리버스(뒤집기), start > stop

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21])

In [42]:
arr[::-1]

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [44]:
arr[-1]

99

In [46]:
arr[-1:50:-1] # arr[-1] == arr[99]

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51])

### 다차원 배열 슬라이싱
- 각 축에 slicing 문법 적용
- 2차원의 경우
    - arr [행 slicing, 열 slicing]
        - `arr[:3, :]`
    - `,` 로 행과 열을 구분한 다중 슬라이싱 사용
- 다차원의 경우
    - arr[0축 slicing, 1축 slicing, ..., n축 slicing]
- slicing과 indexing 문법은 같이 쓸 수 있다.
- 모든 축에 index를 지정할 필요는 없다.

In [53]:
a = np.arange(30).reshape(6,5)
print(a.shape)
print(a)

(6, 5)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [55]:
a[[1,1,1,2,2,2,3,3,3,4,4,4],[1,2,3,1,2,3,1,2,3,1,2,3]]

array([ 6,  7,  8, 11, 12, 13, 16, 17, 18, 21, 22, 23])

In [56]:
a[1:5,1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18],
       [21, 22, 23]])

In [57]:
a[1:5, :]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [58]:
a[1:5] # 1번축 생략 가능 , 앞 축은 불가능.

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [59]:
a[:, 1:3] 

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17],
       [21, 22],
       [26, 27]])

In [60]:
a[,1:3] # 앞 쪽 축은 생략할 수 없다.

SyntaxError: invalid syntax (<ipython-input-60-3b0e7377f26a>, line 1)

In [61]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [65]:
a[:,[1,2]]

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17],
       [21, 22],
       [26, 27]])

In [66]:
a[:,::-1] # 1번 축을 리버싱

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15],
       [24, 23, 22, 21, 20],
       [29, 28, 27, 26, 25]])

In [67]:
a[::-1,:] # 0번 축을 리버싱

array([[25, 26, 27, 28, 29],
       [20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [68]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [69]:
np.flip(a, axis=0) # 0번 축 뒤집기

array([[25, 26, 27, 28, 29],
       [20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [70]:
np.flip(a, axis=1) # 1번 축 뒤집기

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15],
       [24, 23, 22, 21, 20],
       [29, 28, 27, 26, 25]])

In [71]:
np.flip(a) # 모든 축 섞기

array([[29, 28, 27, 26, 25],
       [24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

### 슬라이싱은 원본에 대한 View 
- slicing한 결과는 새로운 배열을 생성하는 것이 아니라 기존 배열을 참조한다.
- slicing한 배열의 원소를 변경하면 원본 배열의 것도 바뀐다.
- 배열.copy()
    - 배열을 복사한 새로운 배열 생성
    - 복사후 처리하면 원본이 바뀌지 않는다.

In [92]:
b = a[:, 1:4]
print(b.shape)
b

(6, 3)


array([[10000,     2,     3],
       [    6,     7,     8],
       [   11,    12,    13],
       [   16,    17,    18],
       [   21,    22,    23],
       [   26,    27,    28]])

In [93]:
b[0,0] = 10000
b

array([[10000,     2,     3],
       [    6,     7,     8],
       [   11,    12,    13],
       [   16,    17,    18],
       [   21,    22,    23],
       [   26,    27,    28]])

In [94]:
b = a[:, 1:4]
b = b.copy()
b

array([[10000,     2,     3],
       [    6,     7,     8],
       [   11,    12,    13],
       [   16,    17,    18],
       [   21,    22,    23],
       [   26,    27,    28]])

In [95]:
b[0,0] = 5000
b

array([[5000,    2,    3],
       [   6,    7,    8],
       [  11,   12,   13],
       [  16,   17,   18],
       [  21,   22,   23],
       [  26,   27,   28]])

In [96]:
a

array([[    0, 10000,     2,     3,     4],
       [    5,     6,     7,     8,     9],
       [   10,    11,    12,    13,    14],
       [   15,    16,    17,    18,    19],
       [   20,    21,    22,    23,    24],
       [   25,    26,    27,    28,    29]])

## boolean indexing
- Index 연산자에 Boolean 배열을 넣으면 True인 index의 값만 조회 (False가 있는 index는 조회하지 않는다.)
- ndarray내의 원소 중에서 원하는 조건의 값들만 조회할 때 사용

In [97]:
a = np.array([1,2,3,4,5])
a.shape

(5,)

In [98]:
b = np.array([True, True, False, False, False])
b.shape

(5,)

In [99]:
a[b]

array([1, 2])

In [100]:
a

array([1, 2, 3, 4, 5])

In [101]:
a[[False, True, False, True, False]]

array([2, 4])

In [102]:
a[[1,3]]

array([2, 4])

In [103]:
# 벡터화 (연산)
# 배열 + 배열 : 같은 인덱스의 원소끼리 연산
a = np.array([1,2,3])
b = np.array([10,20,30])
a + b

array([11, 22, 33])

In [104]:
a + 20

array([21, 22, 23])

In [105]:
a > 2

array([False, False,  True])

In [6]:
arr = np.arange(100)
np.random.shuffle(arr)
arr

array([93, 26, 22, 76, 42, 80, 62, 43, 51, 81, 66, 94, 82, 78,  9, 89, 12,
       20, 68, 84, 13, 63, 21,  4, 73, 14, 74, 86, 85,  8, 69, 60, 30, 23,
       46,  5, 98, 67, 34, 52, 57, 16, 77, 15, 35, 28, 97, 38, 39, 50, 45,
        0, 83, 90,  7, 27, 75, 55,  3, 33, 32, 48, 24, 36, 18, 25, 17, 47,
       79, 19, 44,  1, 53, 71, 70, 41, 56, 59, 65, 96,  6, 61, 92, 88, 54,
       49, 11, 31, 99, 37, 95, 72, 40,  2, 58, 87, 10, 91, 29, 64])

In [7]:
# arr 원소중에서 50 이상인 값들만 조회
arr[arr >= 50]

array([93, 76, 80, 62, 51, 81, 66, 94, 82, 78, 89, 68, 84, 63, 73, 74, 86,
       85, 69, 60, 98, 67, 52, 57, 77, 97, 50, 83, 90, 75, 55, 79, 53, 71,
       70, 56, 59, 65, 96, 61, 92, 88, 54, 99, 95, 72, 58, 87, 91, 64])

In [8]:
arr2 = np.arange(100).reshape(2,50)
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [9]:
arr2 >= 50

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True]])

In [10]:
arr2[arr2>=50]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

## 넘파이에서 비교연산자
- 파이썬 비교 연산자인 and, or, not을 사용못함.
- `&` : and
- `|` : or
- `~` : not
- 피연산자들은 ( )로 묶어야 한다.

In [11]:
# 20~30
(arr >= 20) & (arr <= 30)

array([False,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False,  True,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False])

In [12]:
# 50보다 크지 않은 값들
arr[~ (arr > 50)]

array([26, 22, 42, 43,  9, 12, 20, 13, 21,  4, 14,  8, 30, 23, 46,  5, 34,
       16, 15, 35, 28, 38, 39, 50, 45,  0,  7, 27,  3, 33, 32, 48, 24, 36,
       18, 25, 17, 47, 19, 44,  1, 41,  6, 49, 11, 31, 37, 40,  2, 10, 29])

### np.where()
- np.where(boolean 배열) - True인 index를 반환
- boolean연산과 같이쓰면 특정 조건을 만족하는 원소의 index조회됨.
- np.where(booean 배열, True를 대체할 값, False를 대체할 값)
    - True와 False를 다른 값으로 변경한다.

In [13]:
import numpy as np

In [14]:
a = np.array([True, False, True])
r = np.where(a) # True인 index들을 튜플안에 ndarray에 담아서 반환
print(type(r))
print(r[0])

<class 'tuple'>
[0 2]


In [15]:
# arr에서 50 이상인 값들의 index를 조회
np.where(arr >= 50)

(array([ 0,  3,  5,  6,  8,  9, 10, 11, 12, 13, 15, 18, 19, 21, 24, 26, 27,
        28, 30, 31, 36, 37, 39, 40, 42, 46, 49, 52, 53, 56, 57, 68, 72, 73,
        74, 76, 77, 78, 79, 81, 82, 83, 84, 88, 90, 91, 94, 95, 97, 99],
       dtype=int64),)

In [16]:
np.where(a, '참', '거짓') # True는 참, False 거짓으로 변경한 ndarray 객체 반환

array(['참', '거짓', '참'], dtype='<U2')

In [18]:
np.where(arr >= 50, "50이상", "50미만")

array(['50이상', '50미만', '50미만', '50이상', '50미만', '50이상', '50이상', '50미만',
       '50이상', '50이상', '50이상', '50이상', '50이상', '50이상', '50미만', '50이상',
       '50미만', '50미만', '50이상', '50이상', '50미만', '50이상', '50미만', '50미만',
       '50이상', '50미만', '50이상', '50이상', '50이상', '50미만', '50이상', '50이상',
       '50미만', '50미만', '50미만', '50미만', '50이상', '50이상', '50미만', '50이상',
       '50이상', '50미만', '50이상', '50미만', '50미만', '50미만', '50이상', '50미만',
       '50미만', '50이상', '50미만', '50미만', '50이상', '50이상', '50미만', '50미만',
       '50이상', '50이상', '50미만', '50미만', '50미만', '50미만', '50미만', '50미만',
       '50미만', '50미만', '50미만', '50미만', '50이상', '50미만', '50미만', '50미만',
       '50이상', '50이상', '50이상', '50미만', '50이상', '50이상', '50이상', '50이상',
       '50미만', '50이상', '50이상', '50이상', '50이상', '50미만', '50미만', '50미만',
       '50이상', '50미만', '50이상', '50이상', '50미만', '50미만', '50이상', '50이상',
       '50미만', '50이상', '50미만', '50이상'], dtype='<U4')

In [19]:
# 50 이상인 값은 "50이상"으로 변경하고 50 미만인 값은 그대로 나오도록
np.where(arr>=50, "50이상",arr)

array(['50이상', '26', '22', '50이상', '42', '50이상', '50이상', '43', '50이상',
       '50이상', '50이상', '50이상', '50이상', '50이상', '9', '50이상', '12', '20',
       '50이상', '50이상', '13', '50이상', '21', '4', '50이상', '14', '50이상',
       '50이상', '50이상', '8', '50이상', '50이상', '30', '23', '46', '5', '50이상',
       '50이상', '34', '50이상', '50이상', '16', '50이상', '15', '35', '28',
       '50이상', '38', '39', '50이상', '45', '0', '50이상', '50이상', '7', '27',
       '50이상', '50이상', '3', '33', '32', '48', '24', '36', '18', '25',
       '17', '47', '50이상', '19', '44', '1', '50이상', '50이상', '50이상', '41',
       '50이상', '50이상', '50이상', '50이상', '6', '50이상', '50이상', '50이상',
       '50이상', '49', '11', '31', '50이상', '37', '50이상', '50이상', '40', '2',
       '50이상', '50이상', '10', '50이상', '29', '50이상'], dtype='<U11')

In [21]:
# 0:여성, 1:남성
gender = np.random.choice([0,1], size=20)
gender

array([0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0])

In [22]:
np.where(gender==0,'여성','남성')

array(['여성', '남성', '여성', '남성', '여성', '남성', '남성', '여성', '남성', '남성', '여성',
       '남성', '남성', '여성', '남성', '여성', '여성', '남성', '여성', '여성'], dtype='<U2')

- 2차원도 마찬가지
    - 단 where는 축별로 배열이 반환된다. [0,1], [2,3] => (0,2)  (1,3)
    - 보통 Vector에 적용한다.

In [24]:
arr2 = [
    [1,10,7],
    [4,2,10],
    [10,2,8]
]
arr2 = np.array(arr2)

In [27]:
r = np.where(arr2>=5)
print(type(r))
r
 # 결과 True는 (0,1), (0,2), (1,2), (2,0), (2,2)

<class 'tuple'>


(array([0, 0, 1, 2, 2], dtype=int64), array([1, 2, 2, 0, 2], dtype=int64))

In [28]:
np.where(arr2>=5, '크다', '작다')

array([['작다', '크다', '크다'],
       ['작다', '작다', '크다'],
       ['크다', '작다', '크다']], dtype='<U2')

### 기타
- np.any(boolean 배열)
    - 배열에 True가 하나라도 있으면 True 반환
- np.all(boolean 배열)
    - 배열의 모든 원소가 True이면 True 반환

In [29]:
np.any([False,False,False])

False

In [30]:
np.any([False,True,False])

True

In [31]:
np.all([True,True,True])

True

In [32]:
np.all([True,False,True])

False

In [33]:
np.any(arr > 50) # arr안에 50 초과인 값이 하나라도 있는지?

True

In [34]:
np.all(arr > 50) #arr의 모든 값이 50 초과인지?

False

In [35]:
# 50초과인 값이 몇개?
np.sum(arr > 50)
# sum(): 배열내 원소의 총합계. boolean배열->True:1, False:0 으로 처리후 계산.

49

### 정렬
- np.sort(arr)/ndarray.sort(): arr을 정렬
    - np.sort(배열): 배열을 정렬한 결과를 가진 새로운 배열을 반환(카피본). 원본은 안바뀜
    - 배열.sort() : 원본 배열을 정렬.
- np.argsort(arr): 정렬 후 index를 반환
- 오름차순정렬만 지원. 내림차순을 할 경우 정렬후 reverse 해야 한다.

In [37]:
x = np.sort(arr)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [38]:
arr

array([93, 26, 22, 76, 42, 80, 62, 43, 51, 81, 66, 94, 82, 78,  9, 89, 12,
       20, 68, 84, 13, 63, 21,  4, 73, 14, 74, 86, 85,  8, 69, 60, 30, 23,
       46,  5, 98, 67, 34, 52, 57, 16, 77, 15, 35, 28, 97, 38, 39, 50, 45,
        0, 83, 90,  7, 27, 75, 55,  3, 33, 32, 48, 24, 36, 18, 25, 17, 47,
       79, 19, 44,  1, 53, 71, 70, 41, 56, 59, 65, 96,  6, 61, 92, 88, 54,
       49, 11, 31, 99, 37, 95, 72, 40,  2, 58, 87, 10, 91, 29, 64])

In [41]:
y = arr.sort() # 반환 없이 원본을 바로 정렬
print(y)

None


In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [43]:
arr[::-1]

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [44]:
# 내림차순 정렬
a = np.array([3,1,5,2])
a

array([3, 1, 5, 2])

In [45]:
np.sort(a)[::-1]

array([5, 3, 2, 1])

In [47]:
a

array([3, 1, 5, 2])

In [49]:
np.argsort(a) # sort한 인덱스 알려줌

array([1, 3, 0, 2], dtype=int64)

In [50]:
np.sort(a)

array([1, 2, 3, 5])

In [51]:
# 내림차순
np.argsort(a)[::-1]

array([2, 0, 3, 1], dtype=int64)

In [52]:
a[np.argsort(a)]

array([1, 2, 3, 5])

In [53]:
l = [
    [3,1,5],
    [1,2,9],
    [10,20,5]
]
b = np.array(l)
b

array([[ 3,  1,  5],
       [ 1,  2,  9],
       [10, 20,  5]])

In [57]:
np.sort(b) # 다차원 배열 정렬에서 axis를 생략하면 마지막 축을 기준으로 정렬

array([[ 1,  3,  5],
       [ 1,  2,  9],
       [ 5, 10, 20]])

In [55]:
np.sort(b, axis=0) # 0번축 기준으로 정렬

array([[ 1,  1,  5],
       [ 3,  2,  5],
       [10, 20,  9]])

In [56]:
np.sort(b, axis=1) # 1번축 기준으로 정렬

array([[ 1,  3,  5],
       [ 1,  2,  9],
       [ 5, 10, 20]])